### ISSUE TITLE
1. Get All Markets

### ISSUE THREAD

**Issue by LancePants97** [LancePants97/market_money_2405#5]
1. This endpoint should follow the pattern of `GET /api/v0/markets` and should return ALL markets in the database.
2. In addition to the market’s main attributes, the market resource should also list an attribute for `vendor_count`, which is the number of vendors that are associated with that market.

**Comment by tnoble-cmd** [comment]
'Setup Factory for market. Set up controller for markets. Created Market Serializer and all_markets method. Added jsonape-serializer GEM. US1 complete.

**Comment by tnoble-cmd** [comment]
Sending PR
