### ISSUE TITLE
2. Get ONE Market

### ISSUE THREAD

**Issue by LancePants97** [LancePants97/market_money_2405#6]
1. This endpoint should follow the pattern of `GET /api/v0/markets/:id`
2. If a valid market id is passed in, all market attributes, as well as a `vendor_count` should be returned.
3. If an invalid market id is passed in, a 404 status as well as a descriptive error message should be sent back in the response.

**Comment by tnoble-cmd** [comment]
'Created markets show controller action/serializer method/test for 200 and 404. Handrolled render json: :error. US2 Done.'

PR up
